package task

const (
	TrendTradeCollectionOKEX             = "TrendTradeOKEX"
	TrendTradeCollectionOKEXWithSteps    = "TrendTradeOkexSteps"
	TrendTradeCollectionBinance          = "TrendFundBinance"
	TrendTradeCollectionBitmex           = "TrendFuncCollectionBitmex"
	TrendTradeCollectionFXCM             = "TrendTradeCollectionFXCM"
	TrendTradeCollectionCTP              = "TrendTradeCollectionCTP"
	TrendTradeCollectionOanda            = "TrendTradeCollectionOanda"
	TrendTradeCollectionOanda2           = "TrendTradeCollectionOanda2"
	TrendTradeCollectionCryptoFacilities = "TrendTradeCollectionCryptoFacilities"
	TrendTradeOkexV3                     = "TrendTradeOkexV3"
	TrendTradeOkexV3Spot                 = "TrendTradeOkexV3Spot"
	TrendTradeHuobiSpot                  = "TrendTradeHuobiSpot"
	TrendTradeHuobiDM                    = "TrendTradeHuobiDM"
	TrendTradeIB                         = "TrendTradeIB"
	TrendTradeDeribit                    = "TrendTradeDeribit"

	TrendBalanceOKEX             = "TrendBalanceOKEX"
	TrendBalanceOKEXWithSteps    = "TrendBalanceOKEXSteps"
	TrendBalanceBinance          = "TrendBalanceBinance"
	TrendBalanceBitmex           = "TrendBalanceBitmex"
	TrendBalanceFXCM             = "TrendBalanceFXCM"
	TrendBalanceOanda            = "TrendBalanceOanda"
	TrendBalanceOanda2           = "TrendBalanceOanda2"
	TrendBalanceCTP              = "TrendBalanceCTP"
	TrendBalanceCryptoFacilities = "TrendBalanceCryptoFacilities"
	TrendBalanceOkexV3           = "TrendBalanceOkexV3"
	TrendBalanceOkexV3Spot       = "TrendBalanceOkexV3Spot"
	TrendBalanceHuobiSpot        = "TrendBalanceHuobiSpot"
	TrendBalanceHuobiDM          = "TrendBalanceHuobiDM"
	TrendBalanceIB               = "TrendBalanceIB"
	TrendBalanceDeribit          = "TrendBalanceDeribit"

	TrendFundOKEX             = "TrendFundStructOKEX"
	TrendFundOKEXWithSteps    = "TrendFundOKEXWithSteps"
	TrendFundBinance          = "TrendFundStructBinance"
	TrendFundFXCM             = "TrendFundFXCM"
	TrendFundOanda            = "TrendFundOanda"
	TrendFundCTP              = "TrendFundCTP"
	TrendFundCryptoFacilities = "TrendFundCryptoFacilities"
)
